server:
  port: 7070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false # 禁止注册自己为服务(单机使用)
    fetch-registry: false # 要不要去注册中心获取其他服务的地址(单机使用)
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: false
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85
spring:
  application:
    name: eureka-service